#!/usr/bin/env python3
"""
Generate the embedded UI font from a system TTF.

BeOS drew its interface in Swiss721 at 12 pt, antialiased.  DejaVu Sans at
12 px is the closest metric match available here; the glyphs are baked to
8-bit coverage so the runtime needs no font library and the wasm build
carries the same bytes.

Run: tools/genfont.py > src/tiku_desk_font_data.h

Authors: Ambuj Varshney <ambuj@tiku-os.org>
"""

import sys
from PIL import Image, ImageDraw, ImageFont

CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
]
BOLD = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
]
SIZE = 12
FIRST, LAST = 32, 126


def pick(paths):
    import os
    for p in paths:
        if os.path.exists(p):
            return p
    raise SystemExit("genfont: no candidate font found")


def render(path, name, out):
    font = ImageFont.truetype(path, SIZE)
    asc, desc = font.getmetrics()
    height = asc + desc
    glyphs = []
    blob = []

    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        adv = int(round(font.getlength(ch)))
        box = font.getbbox(ch)
        w = max(1, box[2] - box[0])
        h = max(1, box[3] - box[1])
        img = Image.new("L", (w + 2, h + 2), 0)
        d = ImageDraw.Draw(img)
        d.text((-box[0] + 1, -box[1] + 1), ch, font=font, fill=255)
        px = list(img.getdata())
        # PIL measures from the ascender line; the renderer draws from the
        # baseline, so rebase here rather than in every draw call.
        glyphs.append({
            "cp": cp, "adv": adv,
            "w": img.width, "h": img.height,
            "ox": box[0] - 1, "oy": box[1] - 1 - asc,
            "off": len(blob),
        })
        blob.extend(px)

    out.write("/* %s: %s at %d px, %d glyphs, %d bytes of coverage. */\n"
              % (name, path.rsplit("/", 1)[-1], SIZE, len(glyphs), len(blob)))
    out.write("static const tiku_desk_glyph_t %s_glyphs[] = {\n" % name)
    for g in glyphs:
        out.write("    {%d,%d,%d,%d,%d,%d,%d},\n"
                  % (g["cp"], g["adv"], g["w"], g["h"], g["ox"], g["oy"],
                     g["off"]))
    out.write("};\n")
    out.write("static const unsigned char %s_bits[] = {\n" % name)
    for i in range(0, len(blob), 24):
        out.write("    " + ",".join(str(b) for b in blob[i:i + 24]) + ",\n")
    out.write("};\n")
    out.write("static const tiku_desk_font_t %s_font = {\n"
              "    %s_glyphs, %s_bits, %d, %d, %d, %d\n};\n\n"
              % (name, name, name, len(glyphs), height, asc, FIRST))


def main():
    out = sys.stdout
    out.write("/*\n"
              " * Tiku Desktop -- graphical interface to TikuOS devices.\n"
              " *\n"
              " * Authors: Ambuj Varshney <ambuj@tiku-os.org>\n"
              " *\n"
              " * tiku_desk_font_data.h - baked UI font coverage maps.\n"
              " *\n"
              " * GENERATED by tools/genfont.py -- do not edit by hand.\n"
              " *\n"
              " * SPDX-License-Identifier: Apache-2.0\n"
              " */\n"
              "#ifndef TIKU_DESK_FONT_DATA_H_\n"
              "#define TIKU_DESK_FONT_DATA_H_\n\n")
    render(pick(CANDIDATES), "plain", out)
    render(pick(BOLD), "bold", out)
    out.write("#endif /* TIKU_DESK_FONT_DATA_H_ */\n")


if __name__ == "__main__":
    main()
