/*
 * TikuOS kits -- the foundation TikuDesktop and TikuTracker
 * both stand on.
 *
 * Authors: Ambuj Varshney <ambuj@tiku-os.org>
 *
 * tiku_font.h - the baked UI font.
 *
 * Glyphs are 8-bit coverage maps generated by TikuDesktop/tools/genfont.py,
 * so text is antialiased like R5's and the runtime carries no font library.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef TIKU_FONT_H_
#define TIKU_FONT_H_

#include "tiku_gfx.h"

typedef struct {
    short cp;          /* code point            */
    short adv;         /* advance width         */
    short w, h;        /* coverage map size     */
    short ox, oy;      /* offset from the pen   */
    int   off;         /* index into the blob   */
} tiku_glyph_t;

/**
 * @brief Where a face's glyphs come from, when they are not baked.
 *
 * A face read from a file rasterises what it is asked for and keeps it,
 * so a dropped font draws any letter it HAS -- Greek, Cyrillic, kana --
 * rather than the couple of hundred we would otherwise have guessed at.
 */
typedef struct tiku_face_src tiku_face_src_t;

typedef struct tiku_font {
    const tiku_glyph_t *glyphs;
    const unsigned char     *bits;
    int                      count;
    int                      height;   /* ascent + descent */
    int                      ascent;
    int                      first;
    /* The same face at twice the pixel size, advances forced to exactly
     * double, so a scaled surface can draw REAL detail into the same
     * layout the logical metrics promised.  NULL on the 2x faces. */
    const struct tiku_font *hi;
    /*
     * NULL for a baked face; otherwise the file its glyphs are drawn
     * from and the cache they are kept in.  LAST in the struct because
     * the generated tables initialise the fields above it by position,
     * and a baked face wants this one zero anyway.
     *
     * The cache is mutated through this pointer while the face itself
     * stays const, which is how every caller holds one.
     */
    tiku_face_src_t        *src;
} tiku_font_t;

/**
 * @brief Choose the UI text size in pixels.
 *
 * Snaps down to the nearest baked face (10, 12, 14 or 16 px; BeOS drew
 * its interface at 12).  The pointers already handed out follow the
 * change, so everything laid out from font metrics resizes on its next
 * paint.
 *
 * @return the size actually chosen.
 */
int tiku_font_set_size(int px);

/** @brief The size currently in force. */
int tiku_font_size(void);

/** @brief The UI face at the chosen size (12 px until told otherwise). */
const tiku_font_t *tiku_font_plain(void);

/** @brief How many interface families the toolkit carries. */
int tiku_font_family_count(void);

/** @brief What family @p family is called, or NULL past the last. */
const char *tiku_font_family_name(int family);

/**
 * @brief Choose the family the interface is drawn in.
 *
 * Every family is baked at the same four sizes and within a pixel of the
 * reference face's height, so a switch changes the letters and not the
 * layout.  Out-of-range asks keep the family in force.
 *
 * @return the family actually chosen.
 */
int tiku_font_set_family(int family);

/** @brief The family in force. */
int tiku_font_family(void);

/** @brief What the family in force is called, baked or dropped in. */
const char *tiku_font_current_family(void);

/**
 * @brief Draw the interface with faces read from files.
 *
 * For fonts a person dropped in the fonts folder: the file is parsed and
 * rasterised here, so a device with no font library can be handed a face
 * over a wire and draw with it.  @p bold may be NULL, and then the one
 * face does both weights.
 *
 * @return 1 when the files could be read; the family in force is
 *         unchanged when they could not.
 */
int tiku_font_set_files(const char *regular, const char *bold);

/** @brief Go back to the baked families. */
void tiku_font_use_baked(void);

/*
 * The METRIC REFERENCE rule (after Mac OS 8, which laid out everything
 * against Chicago): all layout is computed against the plain face's
 * metrics, and every other face the toolkit offers -- bold, sized -- must
 * live within them (height within two pixels).  A display face may vary;
 * the geometry it sits in may not.  The kits build no tests of their own,
 * so the assertion that holds this rule lives where the toolkit is
 * exercised, in applications/TikuTracker/tests/test_background.c.
 */

/** @brief The bold face, for window titles and default-button labels. */
const tiku_font_t *tiku_font_bold(void);

/**
 * @brief The plain face nearest @p px, WITHOUT changing the UI size.
 *
 * For chrome that wants a smaller face than the body -- a column title
 * strip at three-quarters of the row text, say -- while the global size
 * stays what the user chose.
 */
const tiku_font_t *tiku_font_at(int px);

/**
 * @brief A face whose every glyph advances the same width.
 *
 * For a terminal grid and nothing else: the interface is laid out
 * against the proportional face above, and mixing the two breaks it.
 *
 * @param bold Nonzero for the heavier face.
 */
const tiku_font_t *tiku_font_mono(int bold);

/** @brief The advance every glyph of the mono face has. */
int tiku_font_mono_cell(int bold);

/** @brief Pixel width of @p text. */
int tiku_text_width(const tiku_font_t *f, const char *text);

/** @brief Line height (ascent + descent). */
int tiku_text_height(const tiku_font_t *f);

/**
 * @brief Draw @p text with its baseline at @p y, left edge at @p x.
 *
 * Coverage is blended against whatever is already on the surface, so text on a
 * bevel or a selection stripe antialiases into the right background.
 */
void tiku_text(tiku_surface_t *s, const tiku_font_t *f,
                    int x, int y, const char *text, tiku_rgb_t c);

/**
 * @brief Draw @p text centred in @p r (both axes).
 *
 * @return The x the text started at, so callers can align related art.
 */
int tiku_text_centered(tiku_surface_t *s, const tiku_font_t *f,
                            tiku_rect_t r, const char *text,
                            tiku_rgb_t c);

#endif /* TIKU_FONT_H_ */
