/*
 * Tiku Operating System v0.06
 * Simple. Ubiquitous. Intelligence, Everywhere.
 * http://tiku-os.org
 *
 * Authors: Ambuj Varshney <ambuj@tiku-os.org>
 *
 * tiku_usbhs_arch.c - EK-RA8P1 USB 2.0 high-speed device controller (U1).
 *
 * Follows the bring-up order the manual draws in Figure 38.2, which is an
 * ORDER with two waits in it, not a set of bits.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stddef.h>

#include "tiku_usbhs_arch.h"
#include "tiku_ra8p1_regs.h"
#include "tiku_cpu_common.h"
#include <kernel/usb/tiku_usbd_msc.h>

/*
 * THE CLOCK QUESTION, SETTLED BY THE MANUAL RATHER THAN BY FAMILY RESEMBLANCE.
 *
 * Every other fast peripheral on this part hides a private clock register
 * behind the PRCR lock -- SCICKCR, GTCLKCR, MRCPC1, SDCKOCR, OCTACKCR -- and
 * USBCKCR exists too, so the natural assumption is that USB needs the same
 * request/ready dance.  It does not, for the mode that matters:
 *
 *   "USBCLK does not need to be supplied when not using USBHS module in
 *    CL-Only mode."                                            (UM 9.10.16)
 *
 * And CL-only mode is exactly the one to avoid, because the manual is equally
 * plain that it cannot do the thing this exists for:
 *
 *   "The clock is generated by supplying 48 MHz and 60 MHz ... and selecting
 *    CL-only mode (PHYSET.HSEB).  High-speed operation is not supported with
 *    this mode."                                               (UM 38.3.3)
 *
 * So high speed means HSEB = 0 and the PHY's own PLL running from the EXTAL
 * pin at 12, 20, 24 or 48 MHz.  This board populates a 24 MHz crystal there
 * and the clock tree is already running on it, so the entire clock story is
 * one field: CLKSEL = 24 MHz.  Nothing to request, nothing to wait for
 * except the PLL's own lock flag.
 */
#define USBHS_CLKSEL_BOARD  RA8P1_PHYSET_CLKSEL_24M

/*
 * PD07 is USBHS_VBUSEN -- the output that switches 5 V ONTO the connector for
 * host mode.  The board manual asks for it low in device mode, and driving it
 * as a plain GPIO output rather than muxing the peripheral function is the
 * safer way to say "never source VBUS": a controller that decides to assert
 * VBUSEN cannot then push 5 V into a host that is already driving it.
 */
#define USBHS_PORT_VBUSEN   0xDU
#define USBHS_PIN_VBUSEN    7U

/*
 * PD04 is USBHS_ID, the OTG role pin: low says A-device (host), high says
 * B-device (device).  Muxing it costs nothing -- it is an input function --
 * and buys the one thing the board manual will not say, which is what its
 * "USBHS Role Toggle" switch actually selects.  A floating read is possible
 * if the board does not wire it, so treat it as evidence, not proof.
 */
#define USBHS_PORT_ID       0xDU
#define USBHS_PIN_ID        4U
#define USBHS_PFS_PSEL_USBHS 0x14U   /* 10100b, per the port function tables */

static uint8_t usbhs_up;

/** @brief Bounded spin for the PLL lock flag, in ~1 us units. */
#define USBHS_PLL_TIMEOUT_US  10000U

static void usbhs_vbusen_low(void)
{
    TIKU_REG8(RA8P1_PWPR_S) = 0U;
    TIKU_REG8(RA8P1_PWPR_S) = (uint8_t)RA8P1_PWPR_PFSWE;
    /* Output, driving low, peripheral mux OFF. */
    TIKU_REG32(RA8P1_PFS(USBHS_PORT_VBUSEN, USBHS_PIN_VBUSEN)) =
        RA8P1_PFS_PDR;
    /* ID as a peripheral input, so SYSSTS0.IDMON reports the role strap. */
    TIKU_REG32(RA8P1_PFS(USBHS_PORT_ID, USBHS_PIN_ID)) =
        ((uint32_t)USBHS_PFS_PSEL_USBHS << RA8P1_PFS_PSEL_SHIFT) |
        RA8P1_PFS_PMR;
    TIKU_REG8(RA8P1_PWPR_S) = (uint8_t)RA8P1_PWPR_B0WI;
    __asm__ volatile ("dsb" ::: "memory");
}

int tiku_ra8p1_usbhs_up(int want_high)
{
    uint16_t v;
    uint32_t spins;

    if (usbhs_up) {
        return TIKU_RA8P1_USBHS_OK;
    }

    /* Ungate first: no register answers while the module is stopped. */
    TIKU_REG32(RA8P1_MSTPCRB) &= ~RA8P1_MSTPB_USBHS;
    (void)TIKU_REG32(RA8P1_MSTPCRB);

    usbhs_vbusen_low();

    /*
     * Operation mode.  DCFM = 0 selects the device controller, and DRPD must
     * be CLEARED rather than left alone: it resets to 1, which is the host's
     * D+/D- pull-downs.  A device that leaves them on is pulling the bus down
     * against the host.
     *
     * CNEN enables the single-ended receivers, and it is NOT optional here.
     * They are what watches D+ and D- individually rather than as a pair, so
     * they are what sees SE0 -- and SE0 held for long enough IS a USB bus
     * reset.  Without CNEN the differential receiver still works, so the part
     * looks alive and SYSSTS0.LNST reads a flat zero forever: a device that
     * cannot notice it is being reset, presenting as a host that ignores it.
     */
    v = TIKU_REG16(RA8P1_USBHS_SYSCFG);
    v &= (uint16_t)~(RA8P1_SYSCFG_DCFM | RA8P1_SYSCFG_DRPD |
                     RA8P1_SYSCFG_DPRPU | RA8P1_SYSCFG_USBE);
    v |= RA8P1_SYSCFG_CNEN;
    if (want_high) {
        v |= RA8P1_SYSCFG_HSE;
    } else {
        v &= (uint16_t)~RA8P1_SYSCFG_HSE;
    }
    TIKU_REG16(RA8P1_USBHS_SYSCFG) = v;

    /*
     * PHY clock: NOT CL-only, reference from EXTAL.  HSEB and CLKSEL are set
     * together and before the waits below, because CLKSEL is ignored once
     * CL-only is selected and the PLL is stopped.
     */
    v = TIKU_REG16(RA8P1_USBHS_PHYSET);
    v &= (uint16_t)~(RA8P1_PHYSET_HSEB | RA8P1_PHYSET_CLKSEL_MASK);
    v |= RA8P1_PHYSET_CLKSEL(USBHS_CLKSEL_BOARD);
    TIKU_REG16(RA8P1_USBHS_PHYSET) = v;
    tiku_cpu_ra8p1_delay_us(2U);                 /* manual asks for 1 us */

    /* Power the transceiver up.  DIRPD resets to 1, so this is the bit that
     * turns the PHY on rather than one that merely tidies it. */
    TIKU_REG16(RA8P1_USBHS_PHYSET) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) & ~RA8P1_PHYSET_DIRPD);
    tiku_cpu_ra8p1_delay_us(1000U);              /* manual asks for 1 ms */

    /*
     * Release the PLL.  One direction only: the manual states operation is
     * not guaranteed if PLLRESET is set back to 1 after being cleared, so
     * there is no "reset the PHY by toggling this" available here -- which is
     * why down() powers the PHY down with DIRPD instead.
     */
    TIKU_REG16(RA8P1_USBHS_PHYSET) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) & ~RA8P1_PHYSET_PLLRESET);

    /* Start the UTMI clock, then wait for the PLL to say it is ready. */
    TIKU_REG16(RA8P1_USBHS_LPSTS) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_LPSTS) | RA8P1_LPSTS_SUSPENDM);

    for (spins = 0U; spins < USBHS_PLL_TIMEOUT_US; spins++) {
        if ((TIKU_REG16(RA8P1_USBHS_PLLSTA) & RA8P1_PLLSTA_PLLLOCK) != 0U) {
            break;
        }
        tiku_cpu_ra8p1_delay_us(1U);
    }
    if (spins >= USBHS_PLL_TIMEOUT_US) {
        /* No lock means no reference: leave the PHY down rather than enable
         * a controller whose clock does not exist. */
        TIKU_REG16(RA8P1_USBHS_PHYSET) =
            (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) | RA8P1_PHYSET_DIRPD);
        return TIKU_RA8P1_USBHS_ERR_CLOCK;
    }

    /*
     * Enable the controller, still detached.  SYSCFG's own note allows this
     * only once CLKSEL is set and PLLLOCK reads 1, which is what the wait
     * above establishes.
     */
    TIKU_REG16(RA8P1_USBHS_SYSCFG) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) | RA8P1_SYSCFG_USBE);

    usbhs_up = 1U;
    return TIKU_RA8P1_USBHS_OK;
}

/*---------------------------------------------------------------------------*/
/* EP0: enumeration (U2)                                                     */
/*---------------------------------------------------------------------------*/
/*
 * The controller decodes the setup packet itself.  On receiving one it sets
 * INTSTS0.VALID, forces DCPCTR.PID to NAK and clears CCPL, then publishes
 * bmRequestType/bRequest/wValue/wIndex/wLength in four registers -- so there
 * is no eight-byte FIFO read to mistime and no way to lose a SETUP to one.
 *
 * The software half is small: clear VALID (until it is clear the pipe cannot be
 * set to BUF and the transfer cannot be ended), move any data through the
 * CFIFO port, then set CCPL with PID at BUF and let the hardware run the
 * status stage in whichever direction the request implied.
 *
 * SET_ADDRESS is answered by the hardware.  The manual is explicit that
 * software must respond to everything EXCEPT a well-formed SET_ADDRESS, so
 * this clears VALID for it and deliberately touches nothing else -- setting
 * CCPL as well would be a second completion for one transfer.
 */

/* pid.codes 1209:0001 is the block that project reserves for prototyping.
 * Borrowing a vendor ID this project does not own would be wrong on a device
 * that plugs into other people's machines; 0001 says "not a product" aloud. */
#define USBD_VID          0x1209U
#define USBD_PID          0x0001U

#define USBD_DESC_DEVICE      1U
#define USBD_DESC_CONFIG      2U
#define USBD_DESC_STRING      3U
#define USBD_DESC_QUALIFIER   6U
#define USBD_DESC_OTHERSPEED  7U

#define USBD_REQ_GET_STATUS        0x00U
#define USBD_REQ_CLEAR_FEATURE     0x01U
#define USBD_REQ_SET_FEATURE       0x03U
#define USBD_REQ_SET_ADDRESS       0x05U
#define USBD_REQ_GET_DESCRIPTOR    0x06U
#define USBD_REQ_GET_CONFIGURATION 0x08U
#define USBD_REQ_SET_CONFIGURATION 0x09U
#define USBD_REQ_GET_INTERFACE     0x0AU
#define USBD_REQ_SET_INTERFACE     0x0BU

#define USBD_EP0_MAXPACKET  64U

#define USBD_CLASS_MSC      0x08U
#define USBD_SUBCLASS_SCSI  0x06U
#define USBD_PROTO_BOT      0x50U

static const uint8_t desc_device[18] = {
    18U, USBD_DESC_DEVICE,
    0x00U, 0x02U,               /* bcdUSB 2.00                              */
    0x00U, 0x00U, 0x00U,        /* class/subclass/protocol: at the interface */
    USBD_EP0_MAXPACKET,
    (uint8_t)USBD_VID, (uint8_t)(USBD_VID >> 8),
    (uint8_t)USBD_PID, (uint8_t)(USBD_PID >> 8),
    0x06U, 0x00U,               /* bcdDevice 0.06                           */
    1U, 2U, 3U,                 /* manufacturer, product, serial            */
    1U                          /* one configuration                        */
};

/*
 * A vendor-specific interface on purpose.  Declaring mass storage here would
 * make Linux bind usb-storage and start issuing commands this milestone
 * cannot answer, so a failure to enumerate and a failure to serve would be
 * entangled.  The endpoints are already the two bulk pipes U3 needs, so only
 * the class triple changes then.
 */
static const uint8_t desc_config[32] = {
    9U, USBD_DESC_CONFIG, 32U, 0U, 1U, 1U, 0U,
    0xC0U,                      /* self-powered                             */
    50U,                        /* 100 mA                                   */
    9U, 4U, 0U, 0U, 2U, USBD_CLASS_MSC, USBD_SUBCLASS_SCSI,
    USBD_PROTO_BOT, 0U,
    7U, 5U, 0x81U, 0x02U, 0x00U, 0x02U, 0U,   /* EP1 IN  bulk 512           */
    7U, 5U, 0x02U, 0x02U, 0x00U, 0x02U, 0U    /* EP2 OUT bulk 512           */
};

/* A high-speed capable device MUST answer these two, and a device that
 * stalls them enumerates at full speed while looking correct. */
static const uint8_t desc_qualifier[10] = {
    10U, USBD_DESC_QUALIFIER, 0x00U, 0x02U,
    0x00U, 0x00U, 0x00U, USBD_EP0_MAXPACKET, 1U, 0U
};

static const uint8_t desc_other_speed[32] = {
    9U, USBD_DESC_OTHERSPEED, 32U, 0U, 1U, 1U, 0U, 0xC0U, 50U,
    9U, 4U, 0U, 0U, 2U, USBD_CLASS_MSC, USBD_SUBCLASS_SCSI,
    USBD_PROTO_BOT, 0U,
    7U, 5U, 0x81U, 0x02U, 0x40U, 0x00U, 0U,   /* full speed: 64-byte bulk   */
    7U, 5U, 0x02U, 0x02U, 0x40U, 0x00U, 0U
};

static const uint8_t desc_lang[4] = { 4U, USBD_DESC_STRING, 0x09U, 0x04U };

/*
 * A trace of what the hardware actually reported for each SETUP, because on
 * this bus the interesting failures are silent: nothing errors, the host
 * simply asks again.  Sixteen entries covers an enumeration attempt.
 */
typedef struct {
    uint16_t req, val, len, ctsq;
    uint16_t dcp_wr, ctr_wr;   /* state right after the bytes were written */
    uint16_t spins;            /* how long BEMP took; 0 = it was already set */
    uint16_t dcp_pre, dcp_post; /* around the status-stage completion        */
    uint8_t  sel_ok, sent_ok;
} ep0_trace_t;

static ep0_trace_t ep0_trace[16];
static uint8_t     ep0_trace_n;
static ep0_trace_t *tr;      /* the entry being filled, or NULL */

/*
 * PIPE1 carries EP1 IN and PIPE2 carries EP2 OUT, matching the descriptors.
 * Both are 512-byte double-buffered bulk pipes, costing (512/64) * 2 = 16
 * blocks of the controller's 8.5 KB buffer each, placed at block 8 and 24 --
 * leaving 0x00 to the DCP and 0x04-0x07 to the pipes that own those numbers.
 */
#define MSC_PIPE_IN     1U          /* device -> host */
#define MSC_PIPE_OUT    2U          /* host -> device */
#define MSC_MPS         512U
#define MSC_BUFSIZE     ((MSC_MPS / 64U) - 1U)
#define MSC_BUFNMB_IN   0x08U
#define MSC_BUFNMB_OUT  0x18U

static uint8_t  ep0_buf[80];
static void pipe_config(uint8_t pipe, uint8_t epnum, int dir_in,
                        uint8_t bufnmb);
static void pipe_pid(uint8_t pipe, uint16_t pid);
static uint8_t  usbhs_config;
static uint32_t n_setup, n_stall;
static uint16_t last_req;

/** @brief Render an ASCII string as a USB string descriptor (UTF-16LE). */
static uint16_t string_desc(const char *s, uint8_t *out)
{
    uint16_t n = 0U;

    out[1] = USBD_DESC_STRING;
    while (*s != '\0' && n < 36U) {
        out[2U + (n * 2U)] = (uint8_t)*s++;
        out[3U + (n * 2U)] = 0U;
        n++;
    }
    out[0] = (uint8_t)(2U + (n * 2U));
    return out[0];
}

/** @brief The board's own unique ID as hex, so two boards differ. */
static uint16_t serial_desc(uint8_t *out)
{
    static const char hex[] = "0123456789ABCDEF";
    char t[17];
    unsigned i;
    uint32_t w0 = TIKU_REG32(RA8P1_UIDR(0));
    uint32_t w1 = TIKU_REG32(RA8P1_UIDR(1));

    for (i = 0U; i < 8U; i++) {
        t[i] = hex[(w0 >> (28U - (4U * i))) & 0xFU];
        t[8U + i] = hex[(w1 >> (28U - (4U * i))) & 0xFU];
    }
    t[16] = '\0';
    return string_desc(t, out);
}

/** @brief Point the CFIFO port at the control pipe and wait for the port. */
static int dcp_select(int writing)
{
    const uint16_t want =
        (uint16_t)(RA8P1_CFIFOSEL_CURPIPE(0U) | RA8P1_CFIFOSEL_MBW_8 |
                   (writing ? RA8P1_CFIFOSEL_ISEL : 0U));
    const uint16_t keep =
        (uint16_t)(RA8P1_CFIFOSEL_ISEL | RA8P1_CFIFOSEL_CURPIPE(0xFU));
    uint32_t spins;

    /*
     * WRITE, THEN CONFIRM BY READING BACK.  The selection crosses into the
     * USB clock domain, so it is not visible the instant it is written -- and
     * FRDY answers for whatever selection is CURRENTLY in effect.  Polling
     * FRDY straight after the write therefore reads the PREVIOUS pipe's
     * readiness, and the bytes that follow go somewhere else: the buffer
     * stays empty, the device NAKs every IN token, and the host times out
     * mid-descriptor with nothing anywhere reporting an error.
     */
    for (spins = 0U; spins < 1000U; spins++) {
        TIKU_REG16(RA8P1_USBHS_CFIFOSEL) = want;
        if ((TIKU_REG16(RA8P1_USBHS_CFIFOSEL) & keep) == (want & keep)) {
            break;
        }
    }
    if (spins >= 1000U) {
        return 0;
    }

    /* Only now is FRDY answering for the pipe just selected. */
    for (spins = 0U; spins < 100000U; spins++) {
        if ((TIKU_REG16(RA8P1_USBHS_CFIFOCTR) & RA8P1_CFIFOCTR_FRDY) != 0U) {
            return 1;
        }
    }
    return 0;
}

static void dcp_pid(uint16_t pid)
{
    TIKU_REG16(RA8P1_USBHS_DCPCTR) =
        (uint16_t)((TIKU_REG16(RA8P1_USBHS_DCPCTR) &
                    ~(uint16_t)RA8P1_DCPCTR_PID_MASK) | pid);
}

/** @brief Refuse the request.  A stall is an answer; silence is not. */
static void ep0_stall(void)
{
    dcp_pid(RA8P1_DCPCTR_PID_STALL);
    n_stall++;
}

/** @brief Finish a transfer that carries no data of ours. */
static void ep0_ack(void)
{
    dcp_pid(RA8P1_DCPCTR_PID_BUF);
    TIKU_REG16(RA8P1_USBHS_DCPCTR) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_DCPCTR) | RA8P1_DCPCTR_CCPL);
}

/**
 * @brief Send up to @p wlen bytes of @p p, then complete the transfer.
 *
 * @param p    bytes to send
 * @param len  how many exist
 * @param wlen how many the host asked for
 */
static void ep0_send(const uint8_t *p, uint16_t len, uint16_t wlen)
{
    uint32_t spins;
    uint16_t n, i;

    /* Never send more than was asked for: a host that requested eight bytes
     * of the device descriptor is sizing EP0 and will not read more. */
    if (len > wlen) {
        len = wlen;
    }

    for (;;) {
        if (!dcp_select(1)) {
            if (tr != NULL) { tr->sel_ok = 0U; }
            ep0_stall();
            return;
        }
        if (tr != NULL) { tr->sel_ok = 1U; }

        /* Clear the DCP's buffer-empty flag first, so the wait below observes
         * THIS packet leaving rather than a previous one's stale flag.
         * Write-0-to-clear: zero the bit to clear, ones everywhere else. */
        TIKU_REG16(RA8P1_USBHS_BEMPSTS) = (uint16_t)~1U;

        n = (len > USBD_EP0_MAXPACKET) ? USBD_EP0_MAXPACKET : len;
        for (i = 0U; i < n; i++) {
            TIKU_REG8(RA8P1_USBHS_CFIFOHH) = p[i];
        }
        p += n;
        len = (uint16_t)(len - n);
        if (tr != NULL) {
            /* Did the buffer actually take the bytes?  BSTS should have gone
             * to 0 (transmission not complete) now that data is staged. */
            tr->dcp_wr = TIKU_REG16(RA8P1_USBHS_DCPCTR);
            tr->ctr_wr = TIKU_REG16(RA8P1_USBHS_CFIFOCTR);
        }

        /* A packet shorter than the maximum must be marked valid to be sent;
         * a full one commits by itself when the buffer fills. */
        if (n < USBD_EP0_MAXPACKET) {
            TIKU_REG16(RA8P1_USBHS_CFIFOCTR) =
                (uint16_t)(TIKU_REG16(RA8P1_USBHS_CFIFOCTR) |
                           RA8P1_CFIFOCTR_BVAL);
        }
        dcp_pid(RA8P1_DCPCTR_PID_BUF);

        /*
         * WAIT FOR THE PACKET TO ACTUALLY GO OUT.  Queueing data only makes
         * it available for the next IN token; the host still has to ask.
         * Completing the transfer before that turns a descriptor read into a
         * status stage over data the host never received -- which is not an
         * error anywhere, just a host that asks again and eventually gives
         * up.  BEMP is the hardware saying the buffer drained.
         */
        for (spins = 0U; spins < 2000000U; spins++) {
            if ((TIKU_REG16(RA8P1_USBHS_BEMPSTS) & 1U) != 0U) {
                break;
            }
        }
        if (tr != NULL) {
            tr->spins = (spins > 0xFFFEU) ? 0xFFFEU : (uint16_t)spins;
        }
        if (spins >= 2000000U) {
            if (tr != NULL) { tr->sent_ok = 0U; }
            return;      /* host walked away; the next SETUP resyncs */
        }
        if (tr != NULL) { tr->sent_ok = 1U; }
        TIKU_REG16(RA8P1_USBHS_BEMPSTS) = (uint16_t)~1U;

        if (len == 0U) {
            break;
        }
    }

    /*
     * Data delivered; now the status stage.  CCPL only takes effect while
     * PID is BUF, and the hardware may have dropped the pipe back to NAK
     * when the packet completed -- so set both in one write rather than
     * assuming BUF survived.
     */
    if (tr != NULL) { tr->dcp_pre = TIKU_REG16(RA8P1_USBHS_DCPCTR); }
    TIKU_REG16(RA8P1_USBHS_DCPCTR) =
        (uint16_t)((TIKU_REG16(RA8P1_USBHS_DCPCTR) &
                    ~(uint16_t)RA8P1_DCPCTR_PID_MASK) |
                   RA8P1_DCPCTR_PID_BUF | RA8P1_DCPCTR_CCPL);
    if (tr != NULL) { tr->dcp_post = TIKU_REG16(RA8P1_USBHS_DCPCTR); }
}

/** @brief GET_DESCRIPTOR, the request enumeration is mostly made of. */
static void ep0_get_descriptor(uint8_t type, uint8_t idx, uint16_t wlen)
{
    uint16_t n;

    switch (type) {
    case USBD_DESC_DEVICE:
        ep0_send(desc_device, sizeof(desc_device), wlen);
        return;
    case USBD_DESC_CONFIG:
        ep0_send(desc_config, sizeof(desc_config), wlen);
        return;
    case USBD_DESC_QUALIFIER:
        ep0_send(desc_qualifier, sizeof(desc_qualifier), wlen);
        return;
    case USBD_DESC_OTHERSPEED:
        ep0_send(desc_other_speed, sizeof(desc_other_speed), wlen);
        return;
    case USBD_DESC_STRING:
        if (idx == 0U) {
            ep0_send(desc_lang, sizeof(desc_lang), wlen);
        } else if (idx == 1U) {
            n = string_desc("TikuOS", ep0_buf);
            ep0_send(ep0_buf, n, wlen);
        } else if (idx == 2U) {
            n = string_desc("EK-RA8P1 USB-HS", ep0_buf);
            ep0_send(ep0_buf, n, wlen);
        } else if (idx == 3U) {
            n = serial_desc(ep0_buf);
            ep0_send(ep0_buf, n, wlen);
        } else {
            ep0_stall();
        }
        return;
    default:
        ep0_stall();
        return;
    }
}

void tiku_ra8p1_usbhs_ep0_poll(void)
{
    uint16_t sts, ctsq, req, val, len;
    uint8_t type, request;

    if (!usbhs_up) {
        return;
    }
    sts = TIKU_REG16(RA8P1_USBHS_INTSTS0);

    /*
     * TRIGGER ON THE STAGE TRANSITION, NOT ON VALID.
     *
     * VALID is set when the setup PACKET arrives, but the manual is careful
     * about the order: the request parameters are stored "when the USBHS
     * receives a data packet FOLLOWING a setup packet".  A poll loop tight
     * enough to land between those two reads USBREQ before it means anything
     * and dispatches on a request the host never sent -- observed directly,
     * as bmRequestType/bRequest pairs of 0x00/0x00 and 0x40/0x00 in a trace
     * where the host was only ever sending GET_DESCRIPTOR.
     *
     * CTRT fires on the stage transition, by which time CTSQ names the stage
     * and the four request registers are populated.  That is the documented
     * mechanism and it has no window.
     */
    if ((sts & RA8P1_INTSTS0_CTRT) == 0U) {
        return;
    }
    ctsq = (uint16_t)(sts & RA8P1_INTSTS0_CTSQ_MASK);

    /* Write-0-to-clear: zero the flag being cleared, ones everywhere else. */
    TIKU_REG16(RA8P1_USBHS_INTSTS0) = (uint16_t)~RA8P1_INTSTS0_CTRT;

    if (ctsq == 6U) {
        /* The controller says the host's sequence made no sense.  Stalling
         * is the defined answer; staying silent is not. */
        ep0_stall();
        return;
    }
    /* 1 = control read data, 3 = control write data, 5 = no-data status.
     * Any other stage is the hardware moving through a transfer already
     * answered, and carries no new request. */
    if (ctsq != 1U && ctsq != 3U && ctsq != 5U) {
        return;
    }

    req     = TIKU_REG16(RA8P1_USBHS_USBREQ);
    val     = TIKU_REG16(RA8P1_USBHS_USBVAL);
    len     = TIKU_REG16(RA8P1_USBHS_USBLENG);
    type    = (uint8_t)(req & 0xFFU);          /* bmRequestType */
    request = (uint8_t)(req >> 8);             /* bRequest      */
    n_setup++;
    last_req = (uint16_t)((request << 8) | type);

    tr = (ep0_trace_n < 16U) ? &ep0_trace[ep0_trace_n++] : NULL;
    if (tr != NULL) {
        tr->req      = req;
        tr->val      = val;
        tr->len      = len;
        tr->ctsq     = ctsq;
        tr->sel_ok   = 0xFFU;
        tr->sent_ok  = 0xFFU;
        tr->dcp_wr   = 0U;
        tr->ctr_wr   = 0U;
        tr->spins    = 0xFFFFU;
        tr->dcp_pre  = 0U;
        tr->dcp_post = 0U;
    }

    /* Clear VALID before responding: while it is set the pipe cannot be put
     * into BUF and the transfer cannot be ended. */
    TIKU_REG16(RA8P1_USBHS_INTSTS0) = (uint16_t)~RA8P1_INTSTS0_VALID;

    /* Answered in hardware.  Touching CCPL here would complete it twice. */
    if (request == USBD_REQ_SET_ADDRESS && type == 0x00U) {
        return;
    }

    switch (request) {
    case USBD_REQ_GET_DESCRIPTOR:
        ep0_get_descriptor((uint8_t)(val >> 8), (uint8_t)(val & 0xFFU), len);
        break;

    case USBD_REQ_SET_CONFIGURATION:
        usbhs_config = (uint8_t)(val & 0xFFU);
        if (usbhs_config != 0U) {
            /* Endpoints only exist once a configuration is selected, and the
             * host expects them freshly reset when it is. */
            pipe_config(MSC_PIPE_IN, 1U, 1, MSC_BUFNMB_IN);
            pipe_config(MSC_PIPE_OUT, 2U, 0, MSC_BUFNMB_OUT);
            pipe_pid(MSC_PIPE_OUT, RA8P1_PIPECTR_PID_BUF);
        }
        ep0_ack();
        break;

    case USBD_REQ_GET_CONFIGURATION:
        ep0_buf[0] = usbhs_config;
        ep0_send(ep0_buf, 1U, len);
        break;

    case USBD_REQ_GET_STATUS:
        /* Self-powered, no remote wakeup. */
        ep0_buf[0] = 0x01U;
        ep0_buf[1] = 0x00U;
        ep0_send(ep0_buf, 2U, len);
        break;

    case USBD_REQ_GET_INTERFACE:
        ep0_buf[0] = 0U;
        ep0_send(ep0_buf, 1U, len);
        break;

    case USBD_REQ_SET_INTERFACE:
    case USBD_REQ_CLEAR_FEATURE:
    case USBD_REQ_SET_FEATURE:
        ep0_ack();
        break;

    default:
        ep0_stall();
        break;
    }
}

uint8_t tiku_ra8p1_usbhs_address(void)
{
    if (!usbhs_up) {
        return 0U;
    }
    return (uint8_t)(TIKU_REG16(RA8P1_USBHS_USBADDR) & 0x7FU);
}

uint8_t tiku_ra8p1_usbhs_configured(void)
{
    return usbhs_config;
}

unsigned tiku_ra8p1_usbhs_ep0_trace(unsigned i, uint16_t *out9)
{
    if (i >= ep0_trace_n || out9 == NULL) {
        return 0U;
    }
    out9[0] = ep0_trace[i].req;
    out9[1] = ep0_trace[i].val;
    out9[2] = ep0_trace[i].len;
    out9[3] = ep0_trace[i].ctsq;
    out9[4] = ep0_trace[i].dcp_wr;
    out9[5] = ep0_trace[i].ctr_wr;
    out9[6] = ep0_trace[i].spins;
    out9[7] = ep0_trace[i].dcp_pre;
    out9[8] = ep0_trace[i].dcp_post;
    return ep0_trace_n;
}

void tiku_ra8p1_usbhs_ep0_stats(uint32_t *setup, uint32_t *stall,
                                uint16_t *last)
{
    if (setup != NULL) { *setup = n_setup; }
    if (stall != NULL) { *stall = n_stall; }
    if (last  != NULL) { *last  = last_req; }
}

/*---------------------------------------------------------------------------*/
/* Bulk pipes and mass storage (U3)                                          */
/*---------------------------------------------------------------------------*/
/*
 * PIPE1 carries EP1 IN and PIPE2 carries EP2 OUT, matching the descriptors
 * U2 already publishes.  Both are 512-byte double-buffered bulk pipes, which
 * costs (512/64) * 2 = 16 blocks of the controller's 8.5 KB buffer each; they
 * are placed at block 8 and block 24, leaving 0x00 to the DCP and 0x04-0x07
 * to the interrupt pipes that own those numbers.
 *
 * Data moves through D0FIFO rather than CFIFO so bulk traffic and control
 * traffic never have to take the port away from each other -- and through it
 * 32 bits at a time, which IS valid at the port's own offset, unlike the
 * 8-bit case that cost U2 a day.
 */
/* The staging disk is the SDRAM window itself: 64 MB, already proven, and
 * the place a model has to end up anyway before it is written to flash. */
#define MSC_DISK_BASE   0x68000000UL
#define MSC_DISK_BYTES  (64UL * 1024UL * 1024UL)

static tiku_usbd_msc_t msc_medium = {
    (uint32_t)(MSC_DISK_BYTES / TIKU_USBD_MSC_BLOCK), "SDRAM Stage", 0U, 0U
};
static uint8_t  msc_reply[TIKU_USBD_MSC_REPLY_MAX];
static uint32_t n_cbw, n_rd, n_wr, n_bad;

/** @brief Configure one bulk pipe.  PID must be NAK while this happens. */
static void pipe_config(uint8_t pipe, uint8_t epnum, int dir_in,
                        uint8_t bufnmb)
{
    TIKU_REG16(RA8P1_USBHS_PIPESEL) = (uint16_t)pipe;

    /* Everything below is only legal while the pipe answers NAK. */
    TIKU_REG16(RA8P1_USBHS_PIPECTR(pipe)) = RA8P1_PIPECTR_PID_NAK;

    TIKU_REG16(RA8P1_USBHS_PIPECFG) =
        (uint16_t)(RA8P1_PIPECFG_TYPE_BULK | RA8P1_PIPECFG_DBLB |
                   (dir_in ? RA8P1_PIPECFG_DIR_IN : 0U) |
                   RA8P1_PIPECFG_EPNUM(epnum));
    TIKU_REG16(RA8P1_USBHS_PIPEBUF) =
        (uint16_t)(RA8P1_PIPEBUF_BUFSIZE(MSC_BUFSIZE) |
                   RA8P1_PIPEBUF_BUFNMB(bufnmb));
    TIKU_REG16(RA8P1_USBHS_PIPEMAXP) = RA8P1_PIPEMAXP_MXPS(MSC_MPS);

    /* Toggle ACLRM to empty both buffers, and reset the data toggle: the
     * host restarts every pipe at DATA0 after SET_CONFIGURATION. */
    TIKU_REG16(RA8P1_USBHS_PIPECTR(pipe)) =
        (uint16_t)(RA8P1_PIPECTR_ACLRM | RA8P1_PIPECTR_PID_NAK);
    TIKU_REG16(RA8P1_USBHS_PIPECTR(pipe)) = RA8P1_PIPECTR_PID_NAK;
    TIKU_REG16(RA8P1_USBHS_PIPECTR(pipe)) =
        (uint16_t)(RA8P1_PIPECTR_SQCLR | RA8P1_PIPECTR_PID_NAK);

    TIKU_REG16(RA8P1_USBHS_PIPESEL) = 0U;
}

static void pipe_pid(uint8_t pipe, uint16_t pid)
{
    TIKU_REG16(RA8P1_USBHS_PIPECTR(pipe)) =
        (uint16_t)((TIKU_REG16(RA8P1_USBHS_PIPECTR(pipe)) &
                    ~(uint16_t)RA8P1_PIPECTR_PID_MASK) | pid);
}

/** @brief Point D0FIFO at @p pipe and wait for the port, as CFIFO needed. */
static int d0_select(uint8_t pipe)
{
    const uint16_t want =
        (uint16_t)(RA8P1_CFIFOSEL_CURPIPE(pipe) | RA8P1_CFIFOSEL_MBW_32);
    uint32_t spins;

    for (spins = 0U; spins < 1000U; spins++) {
        TIKU_REG16(RA8P1_USBHS_D0FIFOSEL) = want;
        if ((TIKU_REG16(RA8P1_USBHS_D0FIFOSEL) & 0xFU) == (uint16_t)pipe) {
            break;
        }
    }
    if (spins >= 1000U) {
        return 0;
    }
    for (spins = 0U; spins < 200000U; spins++) {
        if ((TIKU_REG16(RA8P1_USBHS_D0FIFOCTR) & RA8P1_CFIFOCTR_FRDY) != 0U) {
            return 1;
        }
    }
    return 0;
}

/** @brief Non-zero when the OUT pipe has a packet waiting. */
static int pipe_out_ready(void)
{
    return ((TIKU_REG16(RA8P1_USBHS_PIPECTR(MSC_PIPE_OUT)) &
             RA8P1_PIPECTR_BSTS) != 0U) ? 1 : 0;
}

/**
 * @brief Read one packet from the OUT pipe.
 *
 * @param dst destination
 * @param cap room available
 * @return bytes taken
 */
static uint32_t pipe_read(uint8_t *dst, uint32_t cap)
{
    uint32_t n, i;

    if (!d0_select(MSC_PIPE_OUT)) {
        return 0U;
    }
    n = (uint32_t)(TIKU_REG16(RA8P1_USBHS_D0FIFOCTR) &
                   RA8P1_CFIFOCTR_DTLN_MASK);
    if (n > cap) {
        n = cap;
    }
    /* Words while a whole word remains, then the tail a byte at a time --
     * and the 8-bit tail must use the HH alias, exactly as the DCP does. */
    for (i = 0U; (i + 4U) <= n; i += 4U) {
        uint32_t w = TIKU_REG32(RA8P1_USBHS_D0FIFO);
        dst[i]     = (uint8_t)w;
        dst[i + 1] = (uint8_t)(w >> 8);
        dst[i + 2] = (uint8_t)(w >> 16);
        dst[i + 3] = (uint8_t)(w >> 24);
    }
    if (i < n) {
        uint32_t w = TIKU_REG32(RA8P1_USBHS_D0FIFO);
        while (i < n) {
            dst[i] = (uint8_t)w;
            w >>= 8;
            i++;
        }
    }
    /* Hand the buffer back to the controller. */
    TIKU_REG16(RA8P1_USBHS_D0FIFOCTR) = RA8P1_CFIFOCTR_BCLR;
    return n;
}

/**
 * @brief Send @p len bytes on the IN pipe, in maximum-sized packets.
 *
 * @param src bytes to send
 * @param len how many
 * @return 1 on success, 0 if the host stopped collecting
 */
static int pipe_write(const uint8_t *src, uint32_t len)
{
    uint32_t sent = 0U;

    pipe_pid(MSC_PIPE_IN, RA8P1_PIPECTR_PID_BUF);

    do {
        uint32_t n, i, spins;

        if (!d0_select(MSC_PIPE_IN)) {
            return 0;
        }
        n = ((len - sent) > MSC_MPS) ? MSC_MPS : (len - sent);

        for (i = 0U; (i + 4U) <= n; i += 4U) {
            TIKU_REG32(RA8P1_USBHS_D0FIFO) =
                (uint32_t)src[sent + i] |
                ((uint32_t)src[sent + i + 1] << 8) |
                ((uint32_t)src[sent + i + 2] << 16) |
                ((uint32_t)src[sent + i + 3] << 24);
        }
        for (; i < n; i++) {
            TIKU_REG8(RA8P1_USBHS_D0FIFO + 3UL) = src[sent + i];
        }
        /* Short packets need marking valid; a full buffer commits itself. */
        if (n < MSC_MPS) {
            TIKU_REG16(RA8P1_USBHS_D0FIFOCTR) =
                (uint16_t)(TIKU_REG16(RA8P1_USBHS_D0FIFOCTR) |
                           RA8P1_CFIFOCTR_BVAL);
        }
        sent += n;

        /* Wait for room again before refilling.  Double buffering means this
         * usually returns at once; the bound is for a host that stopped. */
        for (spins = 0U; spins < 4000000U; spins++) {
            if ((TIKU_REG16(RA8P1_USBHS_PIPECTR(MSC_PIPE_IN)) &
                 RA8P1_PIPECTR_BSTS) != 0U) {
                break;
            }
        }
        if (spins >= 4000000U) {
            return 0;
        }
    } while (sent < len);

    return 1;
}

/** @brief Stream a READ(10) out of the staging disk. */
static int msc_send_blocks(uint32_t lba, uint32_t bytes)
{
    const uint8_t *p = (const uint8_t *)(MSC_DISK_BASE +
                                         (lba * TIKU_USBD_MSC_BLOCK));
    return pipe_write(p, bytes);
}

/** @brief Take a WRITE(10) into the staging disk, a packet at a time. */
static int msc_recv_blocks(uint32_t lba, uint32_t bytes)
{
    uint8_t *p = (uint8_t *)(MSC_DISK_BASE + (lba * TIKU_USBD_MSC_BLOCK));
    uint32_t got = 0U;

    pipe_pid(MSC_PIPE_OUT, RA8P1_PIPECTR_PID_BUF);
    while (got < bytes) {
        uint32_t spins;

        for (spins = 0U; spins < 4000000U; spins++) {
            if (pipe_out_ready()) {
                break;
            }
        }
        if (spins >= 4000000U) {
            return 0;
        }
        got += pipe_read(&p[got], bytes - got);
    }
    return 1;
}

void tiku_ra8p1_usbhs_msc_poll(void)
{
    uint8_t raw[TIKU_USBD_MSC_CBW_LEN];
    uint8_t csw[TIKU_USBD_MSC_CSW_LEN];
    tiku_usbd_msc_cbw_t cbw;
    tiku_usbd_msc_cmd_t cmd;
    uint32_t n;
    int ok = 1;

    if (!usbhs_up || usbhs_config == 0U || !pipe_out_ready()) {
        return;
    }

    n = pipe_read(raw, sizeof(raw));
    if (!tiku_usbd_msc_parse_cbw(raw, (uint16_t)n, &cbw)) {
        n_bad++;
        return;      /* not a wrapper; the next packet resyncs */
    }
    n_cbw++;

    /* The SAME decoder the Apollo510 driver uses.  Two controllers, one
     * opinion about what the bytes mean. */
    tiku_usbd_msc_decode(&msc_medium, &cbw, msc_reply, &cmd);

    switch (cmd.action) {
    case TIKU_USBD_MSC_ACT_READ:
        n_rd++;
        ok = msc_send_blocks(cmd.lba, cmd.bytes);
        break;
    case TIKU_USBD_MSC_ACT_WRITE:
        n_wr++;
        ok = msc_recv_blocks(cmd.lba, cmd.bytes);
        break;
    case TIKU_USBD_MSC_ACT_REPLY:
        ok = pipe_write(msc_reply, cmd.len);
        break;
    default:
        break;
    }
    if (!ok) {
        n_bad++;
    }

    tiku_usbd_msc_build_csw(csw, cbw.tag, cmd.residue, cmd.status);
    (void)pipe_write(csw, TIKU_USBD_MSC_CSW_LEN);
}

void tiku_ra8p1_usbhs_msc_stats(uint32_t *cbw, uint32_t *rd, uint32_t *wr,
                                uint32_t *bad)
{
    if (cbw != NULL) { *cbw = n_cbw; }
    if (rd  != NULL) { *rd  = n_rd;  }
    if (wr  != NULL) { *wr  = n_wr;  }
    if (bad != NULL) { *bad = n_bad; }
}

uint32_t tiku_ra8p1_usbhs_msc_hash(uint32_t nblocks)
{
    const uint8_t *p = (const uint8_t *)MSC_DISK_BASE;
    uint32_t h = 2166136261u, i, n;

    if (nblocks == 0U || nblocks > msc_medium.blocks) {
        nblocks = msc_medium.blocks;
    }
    n = nblocks * TIKU_USBD_MSC_BLOCK;
    for (i = 0U; i < n; i++) {
        h = (h ^ p[i]) * 16777619u;
    }
    return h;
}

int tiku_ra8p1_usbhs_attach(int on)
{
    if (!usbhs_up) {
        return TIKU_RA8P1_USBHS_ERR_STATE;
    }
    if (on) {
        TIKU_REG16(RA8P1_USBHS_SYSCFG) =
            (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) | RA8P1_SYSCFG_DPRPU);
    } else {
        TIKU_REG16(RA8P1_USBHS_SYSCFG) =
            (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) & ~RA8P1_SYSCFG_DPRPU);
    }
    __asm__ volatile ("dsb" ::: "memory");
    return TIKU_RA8P1_USBHS_OK;
}

void tiku_ra8p1_usbhs_down(void)
{
    if (!usbhs_up) {
        return;
    }
    TIKU_REG16(RA8P1_USBHS_SYSCFG) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) &
                   ~(RA8P1_SYSCFG_DPRPU | RA8P1_SYSCFG_USBE));
    TIKU_REG16(RA8P1_USBHS_LPSTS) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_LPSTS) & ~RA8P1_LPSTS_SUSPENDM);
    TIKU_REG16(RA8P1_USBHS_PHYSET) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) | RA8P1_PHYSET_DIRPD);
    __asm__ volatile ("dsb" ::: "memory");
    usbhs_up = 0U;
    usbhs_config = 0U;
}

tiku_ra8p1_usbhs_speed_t tiku_ra8p1_usbhs_speed(void)
{
    uint16_t rhst;

    if (!usbhs_up) {
        return TIKU_RA8P1_USBHS_SPEED_NONE;
    }
    rhst = (uint16_t)(TIKU_REG16(RA8P1_USBHS_DVSTCTR0) &
                      RA8P1_DVSTCTR0_RHST_MASK);
    if (rhst == RA8P1_DVSTCTR0_RHST_HIGH) {
        return TIKU_RA8P1_USBHS_SPEED_HIGH;
    }
    if (rhst == RA8P1_DVSTCTR0_RHST_FULL) {
        return TIKU_RA8P1_USBHS_SPEED_FULL;
    }
    return TIKU_RA8P1_USBHS_SPEED_NONE;
}

tiku_ra8p1_usbhs_devstate_t tiku_ra8p1_usbhs_devstate(void)
{
    uint16_t dvsq;

    if (!usbhs_up) {
        return TIKU_RA8P1_USBHS_DEV_POWERED;
    }
    dvsq = (uint16_t)((TIKU_REG16(RA8P1_USBHS_INTSTS0) &
                       RA8P1_INTSTS0_DVSQ_MASK) >> RA8P1_INTSTS0_DVSQ_SHIFT);
    if (dvsq > 3U) {
        return TIKU_RA8P1_USBHS_DEV_SUSPEND;
    }
    return (tiku_ra8p1_usbhs_devstate_t)dvsq;
}

int tiku_ra8p1_usbhs_pll_locked(void)
{
    if (!usbhs_up) {
        return 0;
    }
    return ((TIKU_REG16(RA8P1_USBHS_PLLSTA) & RA8P1_PLLSTA_PLLLOCK) != 0U)
           ? 1 : 0;
}

int tiku_ra8p1_usbhs_id_high(void)
{
    if (!usbhs_up) {
        return -1;
    }
    return ((TIKU_REG16(RA8P1_USBHS_SYSSTS0) & RA8P1_SYSSTS0_IDMON) != 0U)
           ? 1 : 0;
}

int tiku_ra8p1_usbhs_up_state(void)
{
    return (int)usbhs_up;
}

void tiku_ra8p1_usbhs_regs(uint16_t *out, unsigned n)
{
    static const uint32_t addr[] = {
        RA8P1_USBHS_SYSCFG,   RA8P1_USBHS_SYSSTS0,
        RA8P1_USBHS_PLLSTA,   RA8P1_USBHS_DVSTCTR0,
        RA8P1_USBHS_PHYSET,   RA8P1_USBHS_INTSTS0,
        RA8P1_USBHS_LPSTS,    RA8P1_USBHS_FRMNUM
    };
    unsigned i;

    if (out == NULL) {
        return;
    }
    for (i = 0U; i < n; i++) {
        if (i >= sizeof(addr) / sizeof(addr[0])) {
            out[i] = 0U;
        } else if (!usbhs_up &&
                   (TIKU_REG32(RA8P1_MSTPCRB) & RA8P1_MSTPB_USBHS) != 0UL) {
            /* Reading a stopped module hangs the bus rather than returning
             * a value, so say "down" instead of finding that out. */
            out[i] = 0xDEADU;
        } else {
            out[i] = TIKU_REG16(addr[i]);
        }
    }
}
