/*
 * Tiku Operating System v0.06
 * Simple. Ubiquitous. Intelligence, Everywhere.
 * http://tiku-os.org
 *
 * Authors: Ambuj Varshney <ambuj@tiku-os.org>
 *
 * tiku_usbhs_arch.c - EK-RA8P1 USB 2.0 high-speed device controller (U1).
 *
 * Follows the bring-up order the manual draws in Figure 38.2, which is an
 * ORDER with two waits in it, not a set of bits.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stddef.h>

#include "tiku_usbhs_arch.h"
#include "tiku_ra8p1_regs.h"
#include "tiku_cpu_common.h"

/*
 * THE CLOCK QUESTION, SETTLED BY THE MANUAL RATHER THAN BY FAMILY RESEMBLANCE.
 *
 * Every other fast peripheral on this part hides a private clock register
 * behind the PRCR lock -- SCICKCR, GTCLKCR, MRCPC1, SDCKOCR, OCTACKCR -- and
 * USBCKCR exists too, so the natural assumption is that USB needs the same
 * request/ready dance.  It does not, for the mode that matters:
 *
 *   "USBCLK does not need to be supplied when not using USBHS module in
 *    CL-Only mode."                                            (UM 9.10.16)
 *
 * And CL-only mode is exactly the one to avoid, because the manual is equally
 * plain that it cannot do the thing this exists for:
 *
 *   "The clock is generated by supplying 48 MHz and 60 MHz ... and selecting
 *    CL-only mode (PHYSET.HSEB).  High-speed operation is not supported with
 *    this mode."                                               (UM 38.3.3)
 *
 * So high speed means HSEB = 0 and the PHY's own PLL running from the EXTAL
 * pin at 12, 20, 24 or 48 MHz.  This board populates a 24 MHz crystal there
 * and the clock tree is already running on it, so the entire clock story is
 * one field: CLKSEL = 24 MHz.  Nothing to request, nothing to wait for
 * except the PLL's own lock flag.
 */
#define USBHS_CLKSEL_BOARD  RA8P1_PHYSET_CLKSEL_24M

/*
 * PD07 is USBHS_VBUSEN -- the output that switches 5 V ONTO the connector for
 * host mode.  The board manual asks for it low in device mode, and driving it
 * as a plain GPIO output rather than muxing the peripheral function is the
 * safer way to say "never source VBUS": a controller that decides to assert
 * VBUSEN cannot then push 5 V into a host that is already driving it.
 */
#define USBHS_PORT_VBUSEN   0xDU
#define USBHS_PIN_VBUSEN    7U

/*
 * PD04 is USBHS_ID, the OTG role pin: low says A-device (host), high says
 * B-device (device).  Muxing it costs nothing -- it is an input function --
 * and buys the one thing the board manual will not say, which is what its
 * "USBHS Role Toggle" switch actually selects.  A floating read is possible
 * if the board does not wire it, so treat it as evidence, not proof.
 */
#define USBHS_PORT_ID       0xDU
#define USBHS_PIN_ID        4U
#define USBHS_PFS_PSEL_USBHS 0x14U   /* 10100b, per the port function tables */

static uint8_t usbhs_up;

/** @brief Bounded spin for the PLL lock flag, in ~1 us units. */
#define USBHS_PLL_TIMEOUT_US  10000U

static void usbhs_vbusen_low(void)
{
    TIKU_REG8(RA8P1_PWPR_S) = 0U;
    TIKU_REG8(RA8P1_PWPR_S) = (uint8_t)RA8P1_PWPR_PFSWE;
    /* Output, driving low, peripheral mux OFF. */
    TIKU_REG32(RA8P1_PFS(USBHS_PORT_VBUSEN, USBHS_PIN_VBUSEN)) =
        RA8P1_PFS_PDR;
    /* ID as a peripheral input, so SYSSTS0.IDMON reports the role strap. */
    TIKU_REG32(RA8P1_PFS(USBHS_PORT_ID, USBHS_PIN_ID)) =
        ((uint32_t)USBHS_PFS_PSEL_USBHS << RA8P1_PFS_PSEL_SHIFT) |
        RA8P1_PFS_PMR;
    TIKU_REG8(RA8P1_PWPR_S) = (uint8_t)RA8P1_PWPR_B0WI;
    __asm__ volatile ("dsb" ::: "memory");
}

int tiku_ra8p1_usbhs_up(int want_high)
{
    uint16_t v;
    uint32_t spins;

    if (usbhs_up) {
        return TIKU_RA8P1_USBHS_OK;
    }

    /* Ungate first: no register answers while the module is stopped. */
    TIKU_REG32(RA8P1_MSTPCRB) &= ~RA8P1_MSTPB_USBHS;
    (void)TIKU_REG32(RA8P1_MSTPCRB);

    usbhs_vbusen_low();

    /*
     * Operation mode.  DCFM = 0 selects the device controller, and DRPD must
     * be CLEARED rather than left alone: it resets to 1, which is the host's
     * D+/D- pull-downs.  A device that leaves them on is pulling the bus down
     * against the host.
     *
     * CNEN enables the single-ended receivers, and it is NOT optional here.
     * They are what watches D+ and D- individually rather than as a pair, so
     * they are what sees SE0 -- and SE0 held for long enough IS a USB bus
     * reset.  Without CNEN the differential receiver still works, so the part
     * looks alive and SYSSTS0.LNST reads a flat zero forever: a device that
     * cannot notice it is being reset, presenting as a host that ignores it.
     */
    v = TIKU_REG16(RA8P1_USBHS_SYSCFG);
    v &= (uint16_t)~(RA8P1_SYSCFG_DCFM | RA8P1_SYSCFG_DRPD |
                     RA8P1_SYSCFG_DPRPU | RA8P1_SYSCFG_USBE);
    v |= RA8P1_SYSCFG_CNEN;
    if (want_high) {
        v |= RA8P1_SYSCFG_HSE;
    } else {
        v &= (uint16_t)~RA8P1_SYSCFG_HSE;
    }
    TIKU_REG16(RA8P1_USBHS_SYSCFG) = v;

    /*
     * PHY clock: NOT CL-only, reference from EXTAL.  HSEB and CLKSEL are set
     * together and before the waits below, because CLKSEL is ignored once
     * CL-only is selected and the PLL is stopped.
     */
    v = TIKU_REG16(RA8P1_USBHS_PHYSET);
    v &= (uint16_t)~(RA8P1_PHYSET_HSEB | RA8P1_PHYSET_CLKSEL_MASK);
    v |= RA8P1_PHYSET_CLKSEL(USBHS_CLKSEL_BOARD);
    TIKU_REG16(RA8P1_USBHS_PHYSET) = v;
    tiku_cpu_ra8p1_delay_us(2U);                 /* manual asks for 1 us */

    /* Power the transceiver up.  DIRPD resets to 1, so this is the bit that
     * turns the PHY on rather than one that merely tidies it. */
    TIKU_REG16(RA8P1_USBHS_PHYSET) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) & ~RA8P1_PHYSET_DIRPD);
    tiku_cpu_ra8p1_delay_us(1000U);              /* manual asks for 1 ms */

    /*
     * Release the PLL.  One direction only: the manual states operation is
     * not guaranteed if PLLRESET is set back to 1 after being cleared, so
     * there is no "reset the PHY by toggling this" available here -- which is
     * why down() powers the PHY down with DIRPD instead.
     */
    TIKU_REG16(RA8P1_USBHS_PHYSET) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) & ~RA8P1_PHYSET_PLLRESET);

    /* Start the UTMI clock, then wait for the PLL to say it is ready. */
    TIKU_REG16(RA8P1_USBHS_LPSTS) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_LPSTS) | RA8P1_LPSTS_SUSPENDM);

    for (spins = 0U; spins < USBHS_PLL_TIMEOUT_US; spins++) {
        if ((TIKU_REG16(RA8P1_USBHS_PLLSTA) & RA8P1_PLLSTA_PLLLOCK) != 0U) {
            break;
        }
        tiku_cpu_ra8p1_delay_us(1U);
    }
    if (spins >= USBHS_PLL_TIMEOUT_US) {
        /* No lock means no reference: leave the PHY down rather than enable
         * a controller whose clock does not exist. */
        TIKU_REG16(RA8P1_USBHS_PHYSET) =
            (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) | RA8P1_PHYSET_DIRPD);
        return TIKU_RA8P1_USBHS_ERR_CLOCK;
    }

    /*
     * Enable the controller, still detached.  SYSCFG's own note allows this
     * only once CLKSEL is set and PLLLOCK reads 1, which is what the wait
     * above establishes.
     */
    TIKU_REG16(RA8P1_USBHS_SYSCFG) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) | RA8P1_SYSCFG_USBE);

    usbhs_up = 1U;
    return TIKU_RA8P1_USBHS_OK;
}

int tiku_ra8p1_usbhs_attach(int on)
{
    if (!usbhs_up) {
        return TIKU_RA8P1_USBHS_ERR_STATE;
    }
    if (on) {
        TIKU_REG16(RA8P1_USBHS_SYSCFG) =
            (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) | RA8P1_SYSCFG_DPRPU);
    } else {
        TIKU_REG16(RA8P1_USBHS_SYSCFG) =
            (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) & ~RA8P1_SYSCFG_DPRPU);
    }
    __asm__ volatile ("dsb" ::: "memory");
    return TIKU_RA8P1_USBHS_OK;
}

void tiku_ra8p1_usbhs_down(void)
{
    if (!usbhs_up) {
        return;
    }
    TIKU_REG16(RA8P1_USBHS_SYSCFG) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_SYSCFG) &
                   ~(RA8P1_SYSCFG_DPRPU | RA8P1_SYSCFG_USBE));
    TIKU_REG16(RA8P1_USBHS_LPSTS) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_LPSTS) & ~RA8P1_LPSTS_SUSPENDM);
    TIKU_REG16(RA8P1_USBHS_PHYSET) =
        (uint16_t)(TIKU_REG16(RA8P1_USBHS_PHYSET) | RA8P1_PHYSET_DIRPD);
    __asm__ volatile ("dsb" ::: "memory");
    usbhs_up = 0U;
}

tiku_ra8p1_usbhs_speed_t tiku_ra8p1_usbhs_speed(void)
{
    uint16_t rhst;

    if (!usbhs_up) {
        return TIKU_RA8P1_USBHS_SPEED_NONE;
    }
    rhst = (uint16_t)(TIKU_REG16(RA8P1_USBHS_DVSTCTR0) &
                      RA8P1_DVSTCTR0_RHST_MASK);
    if (rhst == RA8P1_DVSTCTR0_RHST_HIGH) {
        return TIKU_RA8P1_USBHS_SPEED_HIGH;
    }
    if (rhst == RA8P1_DVSTCTR0_RHST_FULL) {
        return TIKU_RA8P1_USBHS_SPEED_FULL;
    }
    return TIKU_RA8P1_USBHS_SPEED_NONE;
}

tiku_ra8p1_usbhs_devstate_t tiku_ra8p1_usbhs_devstate(void)
{
    uint16_t dvsq;

    if (!usbhs_up) {
        return TIKU_RA8P1_USBHS_DEV_POWERED;
    }
    dvsq = (uint16_t)((TIKU_REG16(RA8P1_USBHS_INTSTS0) &
                       RA8P1_INTSTS0_DVSQ_MASK) >> RA8P1_INTSTS0_DVSQ_SHIFT);
    if (dvsq > 3U) {
        return TIKU_RA8P1_USBHS_DEV_SUSPEND;
    }
    return (tiku_ra8p1_usbhs_devstate_t)dvsq;
}

int tiku_ra8p1_usbhs_pll_locked(void)
{
    if (!usbhs_up) {
        return 0;
    }
    return ((TIKU_REG16(RA8P1_USBHS_PLLSTA) & RA8P1_PLLSTA_PLLLOCK) != 0U)
           ? 1 : 0;
}

int tiku_ra8p1_usbhs_id_high(void)
{
    if (!usbhs_up) {
        return -1;
    }
    return ((TIKU_REG16(RA8P1_USBHS_SYSSTS0) & RA8P1_SYSSTS0_IDMON) != 0U)
           ? 1 : 0;
}

int tiku_ra8p1_usbhs_up_state(void)
{
    return (int)usbhs_up;
}

void tiku_ra8p1_usbhs_regs(uint16_t *out, unsigned n)
{
    static const uint32_t addr[] = {
        RA8P1_USBHS_SYSCFG,   RA8P1_USBHS_SYSSTS0,
        RA8P1_USBHS_PLLSTA,   RA8P1_USBHS_DVSTCTR0,
        RA8P1_USBHS_PHYSET,   RA8P1_USBHS_INTSTS0,
        RA8P1_USBHS_LPSTS,    RA8P1_USBHS_FRMNUM
    };
    unsigned i;

    if (out == NULL) {
        return;
    }
    for (i = 0U; i < n; i++) {
        if (i >= sizeof(addr) / sizeof(addr[0])) {
            out[i] = 0U;
        } else if (!usbhs_up &&
                   (TIKU_REG32(RA8P1_MSTPCRB) & RA8P1_MSTPB_USBHS) != 0UL) {
            /* Reading a stopped module hangs the bus rather than returning
             * a value, so say "down" instead of finding that out. */
            out[i] = 0xDEADU;
        } else {
            out[i] = TIKU_REG16(addr[i]);
        }
    }
}
