/*
 * Tiku Desktop -- graphical interface to TikuOS devices.
 *
 * Authors: Ambuj Varshney <ambuj@tiku-os.org>
 *
 * tiku_desk_font.h - the baked UI font.
 *
 * Glyphs are 8-bit coverage maps generated by tools/genfont.py, so text is
 * antialiased like R5's and the runtime carries no font library.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef TIKU_DESK_FONT_H_
#define TIKU_DESK_FONT_H_

#include "tiku_desk_gfx.h"

typedef struct {
    short cp;          /* code point            */
    short adv;         /* advance width         */
    short w, h;        /* coverage map size     */
    short ox, oy;      /* offset from the pen   */
    int   off;         /* index into the blob   */
} tiku_desk_glyph_t;

typedef struct tiku_desk_font {
    const tiku_desk_glyph_t *glyphs;
    const unsigned char     *bits;
    int                      count;
    int                      height;   /* ascent + descent */
    int                      ascent;
    int                      first;
    /* The same face at twice the pixel size, advances forced to exactly
     * double, so a scaled surface can draw REAL detail into the same
     * layout the logical metrics promised.  NULL on the 2x faces. */
    const struct tiku_desk_font *hi;
} tiku_desk_font_t;

/** @brief The 12 px UI face (BeOS drew its interface at this size). */
const tiku_desk_font_t *tiku_desk_font_plain(void);

/** @brief The bold face, for window titles and default-button labels. */
const tiku_desk_font_t *tiku_desk_font_bold(void);

/** @brief Pixel width of @p text. */
int tiku_desk_text_width(const tiku_desk_font_t *f, const char *text);

/** @brief Line height (ascent + descent). */
int tiku_desk_text_height(const tiku_desk_font_t *f);

/**
 * @brief Draw @p text with its baseline at @p y, left edge at @p x.
 *
 * Coverage is blended against whatever is already on the surface, so text on a
 * bevel or a selection stripe antialiases into the right background.
 */
void tiku_desk_text(tiku_desk_surface_t *s, const tiku_desk_font_t *f,
                    int x, int y, const char *text, tiku_desk_rgb_t c);

/**
 * @brief Draw @p text centred in @p r (both axes).
 *
 * @return The x the text started at, so callers can align related art.
 */
int tiku_desk_text_centered(tiku_desk_surface_t *s, const tiku_desk_font_t *f,
                            tiku_desk_rect_t r, const char *text,
                            tiku_desk_rgb_t c);

#endif /* TIKU_DESK_FONT_H_ */
