/*
 * Tiku Operating System v0.06
 * Authors: Ambuj Varshney <ambuj@tiku-os.org>
 * tiku_device_esp32c5.h - ESP32-C5 silicon and ROM identity.
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef TIKU_DEVICE_ESP32C5_H_
#define TIKU_DEVICE_ESP32C5_H_

#define TIKU_DEVICE_NAME             "ESP32-C5"
#define TIKU_ESP32C5_HP_SRAM_BASE     0x40800000UL
#define TIKU_ESP32C5_HP_SRAM_SIZE     (384UL * 1024UL)
#define TIKU_ESP32C5_LP_SRAM_BASE     0x50000000UL
#define TIKU_ESP32C5_LP_SRAM_SIZE     (16UL * 1024UL)
#define TIKU_ESP32C5_XTAL_HZ          48000000UL
#define TIKU_ESP32C5_CPU_MAX_HZ       240000000UL
#define TIKU_ESP32C5_IMAGE_CHIP_ID    23UL
#define TIKU_ESP32C5_MIN_ROM_ECO      2UL
#define TIKU_DEVICE_RAM_START        TIKU_ESP32C5_HP_SRAM_BASE
#define TIKU_DEVICE_RAM_SIZE         TIKU_ESP32C5_HP_SRAM_SIZE
#define TIKU_DEVICE_RAM_USABLE       0x4E5A0UL
#define TIKU_DEVICE_IMAGE_WINDOW_START TIKU_DEVICE_RAM_START
#define TIKU_DEVICE_IMAGE_WINDOW_SIZE  0x4E5A0UL
#define TIKU_DEVICE_FRAM_START       0x42000000UL
#define TIKU_DEVICE_FRAM_SIZE        0x400000UL
#define TIKU_DEVICE_FRAM_END         0x423FFFFFUL
#define TIKU_DEVICE_NVM_LABEL        "Flash"
#define TIKU_DEVICE_FRAM_CONFIG_SIZE 576u
#define TIKU_DEVICE_HAS_LFXT         0
#define TIKU_DEVICE_HAS_HFXT         1
#define TIKU_DEVICE_XOSC_HZ          TIKU_ESP32C5_XTAL_HZ
#define TIKU_DEVICE_MAX_STABLE_MHZ    240
#define TIKU_DEVICE_GPIO_COUNT       29

#endif
