#!/usr/bin/env python3
# Tiku Operating System v0.06
#
# mod_embed.py - embed a Tier-3 module image as a C array.
#
# Used on targets whose linker rejects objcopy binary-wrapped objects
# (msp430-elf-ld demands .MSP430.attributes).  Emits the same two symbols
# the objcopy wrap produces (_binary_mod_demo_bin_start/_end), so the
# loader is embed-method-agnostic.
#
# Usage: mod_embed.py <image.bin> <out.c>
#
# SPDX-License-Identifier: Apache-2.0
import sys

if len(sys.argv) != 3:
    sys.exit("usage: mod_embed.py <image.bin> <out.c>")

data = open(sys.argv[1], "rb").read()
rows = [",".join(str(b) for b in data[i:i + 16]) for i in range(0, len(data), 16)]

with open(sys.argv[2], "w") as f:
    f.write("/* Generated by tools/mod_embed.py -- do not edit. */\n")
    f.write("const unsigned char _binary_mod_demo_bin_start[] = {\n")
    f.write(",\n".join(rows))
    f.write("\n};\n")
    f.write('__asm__(".global _binary_mod_demo_bin_end\\n"\n')
    f.write('        "_binary_mod_demo_bin_end = '
            '_binary_mod_demo_bin_start + %d\\n");\n' % len(data))
